test fail

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -3,7 +3,7 @@ name: Pull request
 on:
   push:
     branches:
-      - master
+      - main
       - develop
   pull_request:
     branches:
@@ -33,7 +33,17 @@ jobs:
         run: npm install
 
       - name: Run tests
-        run: npm run test
+        run: npm run test:report
+
+      - name: Test Report
+        uses: drny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: junit.xml
+          fail-on-error: 'false'
+          reporter: jest-junit
+          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: stop containers
         if: always()
